export default {
    ts: "TypeScript",
    js: "JavaScript",
    python: "Python",
    sqlite: "SQLite",
    mongo: "MongoDB",
    postgreSql: "PostgreSQL",
    html: "HTML",
    css: "CSS",
    sass: "SASS",
    scss: "SCSS",
    less: "Less",
    stylus: "Stylus",
    ejs: "EJS",
    jinja: "Jinja2",
    node: "Node.js",
    vscode: "VSCode",
    nvim: "NeoVim",
    figma: "Figma",
    git: "Git & GitHub",
    xfce: "XFCE",
    react: "React",
    discordJs: "Discord.js",
    flask: "Flask",
    quart: "Quart",
    express: "Express",
    rtk: "RTK",
    zod: "Zod",
    webpack: "WebPack",
    pug: "Pug",
    gulp: "Gulp",
    next: "Next",
    deno: "Deno",
    pixijs: "PixiJS",
    preact: "Preact",
    cpp: "C++",
    verilog: "Verilog HDL",
    proteus: "Proteus",
    arduino: "Arduino",
    raspberry: "Raspberry Pi",
    ltspice: "LTspice",
    matlab: "MATLAB",
    vivado: "Vivado",
    scikit: "Scikit-learn",
    pandas: "Pandas",
    numpy: "NumPy",
    tensorflow: "TensorFlow",
    keras: "Keras",
    pytorch: "PyTorch",
    opencv: "OpenCV",
    pyspark: "PySpark",
    nltk: "Natural Language Toolkit (NLTK)",
    dsp: "Digital Signal Processing (DSP)",
    optimization: "Mathematical Optimization Techniques"
}